### ISSUE TITLE
Still presented with SO GUI. 

### ISSUE THREAD

**Issue by Mapmark** [threathunternotebook/SecurityOnion-Ansible-Playbooks#1]
Hi, I'm also trying to automate SO install! 

When I attempt to pass the commands within the playbook, I'm still presented with the GUI asking for the variables.

even using a sample file from SO, it still brings up that issue. Example below.

`sudo ./so-setup network distributed-airgap-manager. `

Is there any insight on this that you're able to help?

**Comment by threathunternotebook** [comment]
Sorry, I just saw this.  Check out the github site: threathunternotebook.
I have the ks.cfg changes, instructions and ansible scripts to automate a
distributed airgap install

**Comment by threathunternotebook** [comment]
Also, ensure it can't connect to a dns server or dns can't resolve the public repos. For some reason the SO scripts try to connect to the Internet if the public repos can be resolved by DNS. I actually see this happen when monitoring the sosetup.log.

**Comment by Mapmark** [comment]
Hey, no worries!

I actually ended up figuring it out and customized the ks accordingly. 

I noticed that it tried to reach out to grab repos even when you're doing an airgap install. So I ended up  just putting an error check to pass on it in the ansible playbook. 

Thanks for the responses!
